### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by scls19fr** [coursera/pandas-ply#6]
Hello,

maybe you should add CI to this project. Travis-CI can help.
You might use miniconda to install Pandas on Travis.

Here is an example https://github.com/scls19fr/pandas_confusion/blob/master/.travis.yml

A much more complex `.travis.yml` file can be find here
https://github.com/pydata/pandas/blob/master/.travis.yml
It can show you how to define a build matrix http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

Kind regards

**Comment by joshuahhh** [comment]
This is a great idea! Thanks for all the pointers.

**Comment by scls19fr** [comment]
you can find below `.travis.yml` files for 2 others projects as example

- https://github.com/pydata/pandas-datareader/blob/master/.travis.yml (Anaconda is installed)
- https://github.com/wavexx/gtabview/blob/master/.travis.yml (default Travis Python version)
